Remove implicit error type conversion from Stream::fold
In my experience it does more harm than good: you need to specify
error type explicitly too often. See e. g. patched test case: it
fails before this commit.

```
stream.fold(0, |a, b| ok(a + b))
```

Without explicit error type parameter of `ok`, compilation fails with:

```
error[E0283]: type annotations required: cannot resolve `u32: std::convert::From<_>`
  --> tests/stream.rs:59:27
   |
59 |     assert_done(|| list().fold(0, |a, b| ok(a + b)), Ok(6));
   |                           ^^^^
```