ci: Work around sanitizer-related regression
```
     Running unittests src/lib.rs (target/debug/deps/futures_macro-cb16371840b70586)

/home/runner/work/futures-rs/futures-rs/target/debug/deps/futures_macro-cb16371840b70586: error while loading shared libraries: libstd-f157c25fb2dbfbe0.so: cannot open shared object file: No such file or directory
error: test failed, to rerun pass `-p futures-macro --lib`

Caused by:
  process didn't exit successfully: `/home/runner/work/futures-rs/futures-rs/target/debug/deps/futures_macro-cb16371840b70586 --skip panic_on_drop_fut` (exit status: 127)
```