Miri: Ignore compat tests
```
error: Undefined Behavior: pointer not dereferenceable: pointer must point to some allocation, but got 0x1[noalloc] which is a dangling pointer (it has no provenance)
   --> /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-0.1.31/src/task_impl/core.rs:135:32
    |
135 |     if GET.compare_exchange(0, get as usize, SeqCst, SeqCst).is_ok() {
    |                                ^^^^^^^^^^^^ Undefined Behavior occurred here
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
    = note: this is on thread `miri_compat_two`
    = note: stack backtrace:
            0: futures::task_impl::core::init
                at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-0.1.31/src/task_impl/core.rs:135:32: 135:44
            1: futures::task_impl::std::set::<{closure@futures::task_impl::Spawn<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>>>::enter<for<'a> fn(&'a mut futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>>) -> std::result::Result<futures::poll::Async<<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>> as futures::future::Future>::Item>, <futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>> as futures::future::Future>::Error> {<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>> as futures::future::Future>::poll}, std::result::Result<futures::poll::Async<()>, ()>>::{closure#0}}, std::result::Result<futures::poll::Async<()>, ()>>::{closure#0}
                at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-0.1.31/src/task_impl/std/mod.rs:66:9: 66:23
            2: std::sync::Once::call_once::<{closure@futures::task_impl::std::set<{closure@futures::task_impl::Spawn<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>>>::enter<for<'a> fn(&'a mut futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>>) -> std::result::Result<futures::poll::Async<<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>> as futures::future::Future>::Item>, <futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>> as futures::future::Future>::Error> {<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>> as futures::future::Future>::poll}, std::result::Result<futures::poll::Async<()>, ()>>::{closure#0}}, std::result::Result<futures::poll::Async<()>, ()>>::{closure#0}}>::{closure#0}
                at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sync/once.rs:166:41: 166:60
            3: futures::task_impl::std::set::<{closure@futures::task_impl::Spawn<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>>>::enter<for<'a> fn(&'a mut futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>>) -> std::result::Result<futures::poll::Async<<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>> as futures::future::Future>::Item>, <futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>> as futures::future::Future>::Error> {<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>> as futures::future::Future>::poll}, std::result::Result<futures::poll::Async<()>, ()>>::{closure#0}}, std::result::Result<futures::poll::Async<()>, ()>>
                at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-0.1.31/src/task_impl/std/mod.rs:63:5: 67:7
            4: futures::task_impl::Spawn::<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>>>::enter::<for<'a> fn(&'a mut futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>>) -> std::result::Result<futures::poll::Async<<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>> as futures::future::Future>::Item>, <futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>> as futures::future::Future>::Error> {<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>> as futures::future::Future>::poll}, std::result::Result<futures::poll::Async<()>, ()>>
                at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-0.1.31/src/task_impl/mod.rs:399:9: 399:34
            5: futures::task_impl::Spawn::<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>>>::poll_fn_notify::<futures_util::compat::compat01as03::WakerToHandle<'_>, for<'a> fn(&'a mut futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>>) -> std::result::Result<futures::poll::Async<<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>> as futures::future::Future>::Item>, <futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>> as futures::future::Future>::Error> {<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>> as futures::future::Future>::poll}, std::result::Result<futures::poll::Async<()>, ()>>
                at /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-0.1.31/src/task_impl/mod.rs:291:9: 291:52
            6: futures::compat::Compat01As03::<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>>>::in_notify::<std::result::Result<futures::poll::Async<()>, ()>, for<'a> fn(&'a mut futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>>) -> std::result::Result<futures::poll::Async<<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>> as futures::future::Future>::Item>, <futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>> as futures::future::Future>::Error> {<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>> as futures::future::Future>::poll}>
                at futures-util/src/compat/compat01as03.rs:40:9: 40:48
            7: <futures::compat::Compat01As03<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>>> as futures::Future>::poll
                at futures-util/src/compat/compat01as03.rs:158:23: 158:57
            8: futures::executor::block_on::<futures::compat::Compat01As03<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>>>>::{closure#0}
                at futures-executor/src/local_pool.rs:319:23: 319:42
            9: futures_executor::local_pool::run_executor::<std::result::Result<(), ()>, {closure@futures::executor::block_on<futures::compat::Compat01As03<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>>>>::{closure#0}}>::{closure#0}
                at futures-executor/src/local_pool.rs:93:37: 93:47
            10: std::thread::LocalKey::<std::sync::Arc<futures_executor::local_pool::ThreadNotify>>::try_with::<{closure@futures_executor::local_pool::run_executor<std::result::Result<(), ()>, {closure@futures::executor::block_on<futures::compat::Compat01As03<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>>>>::{closure#0}}>::{closure#0}}, std::result::Result<(), ()>>
                at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:464:12: 464:27
            11: std::thread::LocalKey::<std::sync::Arc<futures_executor::local_pool::ThreadNotify>>::with::<{closure@futures_executor::local_pool::run_executor<std::result::Result<(), ()>, {closure@futures::executor::block_on<futures::compat::Compat01As03<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>>>>::{closure#0}}>::{closure#0}}, std::result::Result<(), ()>>
                at /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/local.rs:428:15: 428:31
            12: futures_executor::local_pool::run_executor::<std::result::Result<(), ()>, {closure@futures::executor::block_on<futures::compat::Compat01As03<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>>>>::{closure#0}}>
                at futures-executor/src/local_pool.rs:89:5: 105:7
            13: futures::executor::block_on::<futures::compat::Compat01As03<futures::compat::Compat<std::pin::Pin<std::boxed::Box<{async block@futures/tests/compat_miri.rs:7:15: 7:20}>>>>>
                at futures-executor/src/local_pool.rs:319:5: 319:43
            14: miri_compat_two_way
                at futures/tests/compat_miri.rs:11:5: 11:18
            15: miri_compat_two_way::{closure#0}
                at futures/tests/compat_miri.rs:6:25: 6:25
```