Fix rustdoc::redundant_explicit_links warning
```
error: redundant explicit link target
   --> futures-executor/src/local_pool.rs:314:25
    |
314 | /// Use a [`LocalPool`](LocalPool) if you need finer-grained control over
    |            -----------  ^^^^^^^^^ explicit target is redundant
    |            |
    |            because label contains path that resolves to same destination
    |
    = note: when a link's destination is not specified,
            the label is used to resolve intra-doc links
    = note: `-D rustdoc::redundant-explicit-links` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(rustdoc::redundant_explicit_links)]`
help: remove explicit link target
    |
314 | /// Use a [`LocalPool`] if you need finer-grained control over
    |           ~~~~~~~~~~~~~

error: redundant explicit link target
  --> futures-executor/src/local_pool.rs:37:33
   |
37 | /// A handle to a [`LocalPool`](LocalPool) that implements
   |                    -----------  ^^^^^^^^^ explicit target is redundant
   |                    |
   |                    because label contains path that resolves to same destination
   |
   = note: when a link's destination is not specified,
           the label is used to resolve intra-doc links
help: remove explicit link target
   |
37 | /// A handle to a [`LocalPool`] that implements
   |                   ~~~~~~~~~~~~~
```